FROM jupyter/pyspark-notebook

COPY ./data /home/jovyan/work/data/
COPY ./source /home/jovyan/work/

USER root

# Change ownership and permissions
RUN chown -R jovyan:users /home/jovyan/work/ && \
    chmod -R g+w /home/jovyan/work/

# Switch back to the jovyan user
USER jovyan
