FROM python:3.12.6-bookworm
RUN pip3 install poetry
WORKDIR /home/pyspark
COPY . /home/pyspark
RUN poetry config virtualenvs.in-project true
RUN poetry install --no-root
COPY create_kafka_topic.sh /usr/local/bin/create_kafka_topic.sh
RUN chmod +x /usr/local/bin/create_kafka_topic.sh
ENV PATH="/home/pyspark/.venv/bin:$PATH"
ENTRYPOINT ["poetry", "run", "python", "main.py"]
